export const FETCHED_USER_FULFILLED = 'FETCHED_USER_FULFILLED';
export const FETCHED_USER_PENDING = 'FETCHED_USER_PENDING';
export const FETCHED_USER_REJECTED = 'FETCHED_USER_REJECTED';
export const SET_USER_NAME = 'SET_USER_NAME';
