export const DRAWER_OPEN = 'NAVIGATION.DRAWER_OPEN';
export const DRAWER_CLOSE = 'NAVIGATION.DRAWER_CLOSE';
export const DRAWER_TOGGLE = 'NAVIGATION.DRAWER_TOGGLE';
export const PUSH_ROUTE = 'NAVIGATION.PUSH_ROUTE';
export const POP_ROUTE = 'NAVIGATION.POP_ROUTE';
