export const FETCHED_FULFILLED = 'USER.FETCHED_FULFILLED';
export const FETCHED_PENDING = 'USER.FETCHED_PENDING';
export const FETCHED_REJECTED = 'USER.FETCHED_REJECTED';
export const SET_NAME = 'USER.SET_NAME';
